version = 1

[[annotations]]
path = ["lib/*.lib"]
SPDX-FileCopyrightText = "2025 Soulfind Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["dub.json"]
SPDX-FileCopyrightText = "2024-2025 Soulfind Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = [
    "2024-2026 Soulfind Contributors",
    "2005 SeeSchloss <seeschloss@seeschloss.org>"
]
SPDX-License-Identifier = "GPL-3.0-or-later"
