# SPDX-FileCopyrightText: 2024 Soulfind Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = ["lib/*.lib"]
SPDX-FileCopyrightText = "2025 Soulfind Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["dub.*"]
SPDX-FileCopyrightText = "2024-2025 Soulfind Contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
